### PR TITLE
uefi/me: check for valid Offset and add Type, fix #293

### LINKED ISSUE #293: tighten_me command fails with up board image
rminnich@xcpu:~/projects/linuxboot/mainboards/aeeon/up$ utk uprom.bin tighten_me save x.bin
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/linuxboot/fiano/pkg/visitors.(*TightenME).process(0xc00000c080, 0x5de8a0, 0xc00000c080)
	/home/rminnich/gopath/src/github.com/linuxboot/fiano/pkg/visitors/tightenme.go:74 +0xab4
github.com/linuxboot/fiano/pkg/visitors.(*TightenME).Run(0xc00000c080, 0x5dfde0, 0xc00008c1e0, 0x0, 0x0)
	/home/rminnich/gopath/src/github.com/linuxboot/fiano/pkg/visitors/tightenme.go:29 +0x12b
github.com/linuxboot/fiano/pkg/visitors.ExecuteCLI(0x5dfde0, 0xc00008c1e0, 0xc00000c0a0, 0x2, 0x2, 0x0, 0x0)
	/home/rminnich/gopath/src/github.com/linuxboot/fiano/pkg/visitors/cli.go:68 +0x6d
github.com/linuxboot/fiano/pkg/utk.Run(0xc000010060, 0x4, 0x4, 0x4, 0x0)
	/home/rminnich/gopath/src/github.com/linuxboot/fiano/pkg/utk/utk.go:59 +0x23f
main.main()
	/home/rminnich/gopath/src/github.com/linuxboot/fiano/cmds/utk/utk.go:75 +0x9e

### PR DESCRIPTION
**Pull request by JulienVdG**
Signed-off-by: Julien Viard de Galbert <julien.viard-de-galbert@itrenew.com>

### CODE REVIEW

File: pkg/uefi/meregion.go [hunk 1]
```diff
@@ -48,7 +48,8 @@ type MEPartitionEntry struct {
 	Owner    [4]byte
 	Offset   uint32
 	Length   uint32
-	Reserved [4]uint32
+	Reserved [3]uint32
```
Comment (rminnich) [inline pkg/uefi/meregion.go]: You can name this _ if you want. Do you need the Reserved here for some reason? Did you want to save the value of Reserved bits?

Comment (GanShun) [reply pkg/uefi/meregion.go]: Would advise preserving the value of Reserved bits.

Comment (JulienVdG) [reply pkg/uefi/meregion.go]: Currently it's only used for parsing and the full buffer is preserved, but if for some reasons we want to go in more detailed analysis and modification, it's better to keep the content of those fields. Especially since they mostly are not reserved anymore but the documentation I used (older versions of ME) listed them as reserved.
